"""fix_enum_constraint_metadata

Revision ID: ce529a67fc63
Revises: aefe4d0f06dc
Create Date: 2026-08-09 18:01:08.548248

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision: str = 'ce529a67fc63'
down_revision: str | Sequence[str] | None = 'aefe4d0f06dc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agent_run_status'), 'agent_runs', type_='check')
    op.drop_constraint(op.f('order_side'), 'orders', type_='check')
    op.drop_constraint(op.f('order_status'), 'orders', type_='check')
    op.drop_constraint(op.f('order_type'), 'orders', type_='check')
    op.drop_constraint(op.f('signal_action'), 'signals', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('signal_action'), 'signals', "action::text = ANY (ARRAY['BUY'::character varying, 'SELL'::character varying, 'HOLD'::character varying]::text[])")
    op.create_check_constraint(op.f('order_type'), 'orders', "order_type::text = ANY (ARRAY['MARKET'::character varying, 'LIMIT'::character varying, 'STOP'::character varying, 'STOP_LIMIT'::character varying]::text[])")
    op.create_check_constraint(op.f('order_status'), 'orders', "status::text = ANY (ARRAY['NEW'::character varying, 'PENDING'::character varying, 'PARTIALLY_FILLED'::character varying, 'FILLED'::character varying, 'CANCELLED'::character varying, 'REJECTED'::character varying]::text[])")
    op.create_check_constraint(op.f('order_side'), 'orders', "side::text = ANY (ARRAY['BUY'::character varying, 'SELL'::character varying]::text[])")
    op.create_check_constraint(op.f('agent_run_status'), 'agent_runs', "status::text = ANY (ARRAY['RUNNING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying]::text[])")
    # ### end Alembic commands ###
