"""Safe adapter boundary for TradingAgents reasoning.

The existing daily_stock_analyse engine remains the source of truth for market
signals. This module deliberately does not fetch market data or place orders.
It converts an imported AI Henge Fund signal into a stable reasoning request
that can later be delegated to a real TradingAgents runtime.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol


@dataclass(frozen=True)
class TradingAgentsDecision:
    """Normalized result returned by the reasoning layer."""

    action: str
    confidence: float | None
    rationale: str
    provider: str


class TradingAgentsRuntime(Protocol):
    """Minimal runtime contract so the repository is not coupled to a fork."""

    def analyze(self, request: dict[str, Any]) -> TradingAgentsDecision: ...


class TradingAgentsBridge:
    """Build deterministic reasoning requests and optionally call a runtime."""

    def __init__(self, runtime: TradingAgentsRuntime | None = None) -> None:
        self._runtime = runtime

    @property
    def enabled(self) -> bool:
        return self._runtime is not None

    def build_request(self, signal: Any) -> dict[str, Any]:
        """Convert an imported signal into a provider-neutral request."""
        return {
            "symbol": signal.symbol,
            "action": signal.action.value if hasattr(signal.action, "value") else str(signal.action),
            "confidence": float(signal.confidence) if signal.confidence is not None else None,
            "target_price": (
                float(signal.target_price) if signal.target_price is not None else None
            ),
            "reasoning": signal.reasoning,
            "source": signal.source,
            "source_signal_id": signal.source_signal_id,
            "generated_at": signal.generated_at.isoformat() if signal.generated_at else None,
        }

    def analyze(self, signal: Any) -> TradingAgentsDecision:
        """Analyze one signal, requiring an explicitly configured runtime."""
        if self._runtime is None:
            raise RuntimeError(
                "TradingAgents runtime is not configured. Set up the provider adapter "
                "before enabling AI reasoning in production."
            )
        return self._runtime.analyze(self.build_request(signal))


class PassthroughTradingAgentsRuntime:
    """Safe development runtime used until the real TradingAgents package is wired in."""

    def analyze(self, request: dict[str, Any]) -> TradingAgentsDecision:
        return TradingAgentsDecision(
            action=request["action"],
            confidence=request["confidence"],
            rationale=(
                "TradingAgents adapter received the imported daily_stock_analyse signal; "
                "no independent market decision was generated by the development runtime."
            ),
            provider="tradingagents-passthrough",
        )
